2025-06-04 00:54:16,404 - root - INFO - Logging to E:\EmotionAnalysis\Emotions-Analysis\outputs\logs\20250604_005416_training.log
2025-06-04 00:54:16,404 - root - INFO - Starting training pipeline...
2025-06-04 00:54:16,404 - root - INFO - Using device: cuda
2025-06-04 00:54:16,811 - root - INFO - Loaded tokenizer with vocab size: 30522
2025-06-04 00:54:16,812 - root - INFO - Loading data from raw files...
2025-06-04 00:54:16,812 - root - INFO - Loading raw data...
2025-06-04 00:54:17,217 - root - INFO - Data sizes - Train: 5548, Val: 686, Test: 693
2025-06-04 00:54:17,217 - root - INFO - Data loaded - Train: 5548, Val: 686, Test: 693
2025-06-04 00:54:17,217 - root - INFO - Train set unique emotions: [6 5 0 2 3 1 4]
2025-06-04 00:54:17,228 - root - INFO - Val set unique emotions: [6 0 1 2 4 5 3]
2025-06-04 00:54:17,228 - root - INFO - Creating datasets...
2025-06-04 00:54:17,228 - root - INFO - Setting vocab size to 30522
2025-06-04 00:54:17,228 - root - INFO - Creating dataloaders...
2025-06-04 00:54:17,229 - root - INFO - Initializing trainer...
2025-06-04 00:54:17,494 - root - INFO - Starting training...
2025-06-04 00:54:47,229 - root - ERROR - An error occurred: 'TrainingConfig' object has no attribute 'focal_weight'
Traceback (most recent call last):
  File "E:\EmotionAnalysis\Emotions-Analysis\main.py", line 108, in main
    train_results = trainer.train(train_loader, val_loader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\EmotionAnalysis\Emotions-Analysis\src\trainer\train.py", line 217, in train
    train_metrics = self.train_epoch(train_loader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\EmotionAnalysis\Emotions-Analysis\src\trainer\train.py", line 132, in train_epoch
    focal_weight=self.config.training.focal_weight
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingConfig' object has no attribute 'focal_weight'
